apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sargvision-frontend
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/cpu-throttling: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/${PROJECT_ID}/sargvision-frontend
          ports:
            - name: http1
              containerPort: 3000
          resources:
            limits:
              cpu: '1000m'
              memory: '1024Mi'
          env:
            - name: NEXT_PUBLIC_API_URL
              value: ${NEXT_PUBLIC_API_URL}
            - name: NEXT_PUBLIC_SUPABASE_URL
              value: ${NEXT_PUBLIC_SUPABASE_URL}
            - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
              value: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
