apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sargvision-api
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/cpu-throttling: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/${PROJECT_ID}/sargvision-api
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: '1000m'
              memory: '1024Mi'
          env:
            - name: ENV
              value: prod
            - name: SUPABASE_DB_URL
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_DB_URL
                  key: latest
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_API_KEY
                  key: latest
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: TWILIO_ACCOUNT_SID
                  key: latest
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: TWILIO_AUTH_TOKEN
                  key: latest
            - name: TWILIO_WHATSAPP_NUMBER
              valueFrom:
                secretKeyRef:
                  name: TWILIO_WHATSAPP_NUMBER
                  key: latest
